### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by korymath** [twitter/torch-twrl#25]
package as docker for easy modularity

**Comment by korymath** [comment]
Note: @kaixhin added to https://github.com/Kaixhin/docker-torch-mega

**Comment by davemssavage** [comment]
Hi I have a couple of patches for docker support here:

https://github.com/davemssavage/gym-http-api/blob/docker/Dockerfile

And here:

https://github.com/davemssavage/torch-twrl/blob/docker/Dockerfile

**Comment by korymath** [comment]
Very nice. Thinking along the same lines. 
Whats the status of the patches? Usable and tested?

**Comment by davemssavage** [comment]
Yep both superficiallly both seem to work. Tested Atari, cartpole and pendulum tasks.

There's some notes here if you want to verify:

https://hub.docker.com/r/davemssavage/torch-twrl/

The gym-http-api docker file is dependent on a patch to support updating the bind address:

https://github.com/openai/gym-http-api/pull/18
