### ISSUE TITLE
Silent Server Error: bad argument #1 to '?'

### ISSUE THREAD

**Issue by JadenTravnik** [twitter/torch-twrl#26]
The client needs to see more information when this error occurs.

Reproduced by stopping the server while running or a dropped packet from the server.

It would be nice if the experiment could do one of the following:
- restart the whole run (useful for short runs)
- save the agent's information (weights, traces, etc) before restarting the episode and resetting the agent with that information (useful for long runs)

**Comment by korymath** [comment]
Error looks like this: 

bad argument #1 to '?' (expecting number or torch.DoubleTensor or torch.DoubleStorage at /home/kory/torch/pkg/torch/generic/Tensor.c:1125) 
Error: Experiment was not successfully run.

from the sweep.sh example

Unclear where it is being thrown.

**Comment by korymath** [comment]
Added a stack trace on throw, easier to debug based on algorithm specific errors.
