### ISSUE TITLE
Inconsistent types with boolean variables

### ISSUE THREAD

**Issue by SeanNaren** [twitter/torch-twrl#34]
I've noticed strange behaviour with `-verboseUpdate` param since it defaults to false. The other boolean variables return strings of true or false, however this returns an actual boolean. This is probably also the case for any variables that default to true! 

I would suggest making all booleans default to false, however there might be a better way to solve this.

This is also fixed by [this](https://github.com/twitter/torch-twrl/commit/6e82e25262e5521de5bd2170270ce1a7681816a8) by checking for both conditions, but might be worth defaulting to false for uniformity!

**Comment by korymath** [comment]
good call!
